#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
from erl_exporter import ErlSimpleConverter, ErlRecordConverter, ErlArrayConverter
from erl_processor import *
from check_processor import *

exporters = {
    'Character_recommend.xls' : ErlRecordConverter('data_charater_recommend',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl'
                                    ),
    'AttributeSwitch.xls' : ErlRecordConverter('data_attribute_switch',
                                        key_fields = ['class'],
                                        header_file = 'data.hrl',
                                        include_key_fields = False),
    'FunctionCondition.xls' : ErlSimpleConverter('data_function_condition',
                                    key_fields = ['id'],
                                    value_field = 'variable'),
    'Item.xls' : ErlRecordConverter('data_item',
                                    get_all = True,
                                    key_fields = ['id'],
                                    header_file = 'data.hrl'),
    'Compose.xls' : ErlRecordConverter('data_item_compose',
									get_all = True,
                                    key_fields = ['compose_id'],
                                    header_file = 'data.hrl'
                                    ),
    'Exp.xls' : ErlRecordConverter('data_exp',
                                    key_fields = ['level'],
                                    header_file = 'data.hrl'
                                    ),
    'GangAuthority.xls' : ErlRecordConverter('data_gang_authority',
                                    get_all = True,
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    processor = gang_authority_processor
                                    ),
    'GangLevelUp.xls' : ErlRecordConverter('data_gang_level_up',
                                    get_all = True,
                                    key_fields = ['level'],
                                    header_file = 'data.hrl',
                                    processor = gang_level_up_processor
                                    ),
    'GangSkill.xls' : ErlRecordConverter('data_gang_skill',
                                    get_all = True,
                                    key_fields = ['id'],
                                    header_file = 'data.hrl'
                                    ),
    'GangSkillAttribute.xls' : ErlRecordConverter('data_gang_skill_attribute',
                                    get_all = True,
                                    key_fields = ['level'],
                                    header_file = 'data.hrl'
                                    ),
     'GangSkillLearn.xls' : ErlRecordConverter('data_gang_skill_learn',
                                    get_all = True,
                                    key_fields = ['level'],
                                    header_file = 'data.hrl'
                                    ),
     'Question.xls' : ErlRecordConverter('data_question',
                                    get_all = True,
                                    key_fields = ['id'],
                                    header_file = 'data.hrl'
                                    ),
     'Charge.xls' : ErlRecordConverter('data_charge',
                                    get_all = True,
                                    key_fields = ['id'],
                                    header_file = 'data.hrl'
                                    ),
     'SevenChargeReward.xls' : ErlRecordConverter('data_seven_charge_reward',
                                    get_all = True,
                                    key_fields = ['id'],
                                    header_file = 'data.hrl'
                                    ),
     'PlatformGifts.xls' : ErlRecordConverter('data_platformgifts',
                                    get_all = True,
                                    key_fields = ['item_id'],
                                    header_file = 'data.hrl'
                                    ),
     'GangBattleReward.xls' : ErlRecordConverter('data_gang_battle_reward',
                                    key_fields = [],
                                    compare_item = ('min_rank', 'max_rank'),
                                    header_file = 'data.hrl'
                                    ),
     'GangBattleWin.xls' : ErlRecordConverter('data_gang_battle_win',
                                    key_fields = ['time'],
                                    compare_item = ('min_worldlv', 'max_worldlv'),
                                    header_file = 'data.hrl'
                                    ),
     'Crystal.xls' : ErlRecordConverter('data_crystal',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    get_all = True
                                    ),
    #'Skill.xls' : ErlRecordConverter('data_skill',
    #                                 key_fields = ['id'],
    #                                 header_file = 'data.hrl',
    #                                 get_all = True),
    'Skill.xls' : ErlRecordConverter('data_skill',
                                     key_fields = ['id'],
                                     header_file = 'skill.hrl',
                                     get_all = True),
    'Skill_Core.xls' : ErlRecordConverter('data_skill_core',
                                     key_fields = ['id'],
                                     header_file = 'skill.hrl',
                                     get_all = True,
                                     processor = skill_core_processor),
    'Skill_Trigger.xls' : ErlRecordConverter('data_skill_trigger',
                                     key_fields = ['id'],
                                     header_file = 'skill.hrl',
                                     get_all = True,
                                     processor = skill_trigger_processor),
    'Skill_Buff.xls' : ErlRecordConverter('data_skill_buff',
                                     key_fields = ['id'],
                                     header_file = 'skill.hrl',
                                     get_all = True,
                                     processor = skill_buff_processor),
    'Buff.xls' : ErlRecordConverter('data_buff',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    processor = buff_processor),
    'Scene.xls' : ErlRecordConverter('data_scene',
                                    key_fields = ['id'],
                                    record_name = 'data_scene',
                                    header_file = 'scene.hrl',
                                    get_all = True),
    'JumpPoint.xls' : ErlRecordConverter('data_jump_point',
                                    key_fields = ['id'],
                                    record_name = 'data_jump_point',
                                    header_file = 'scene.hrl',
                                    get_all = True),
    'Mate.xls' : ErlRecordConverter('data_mate',
                                     key_fields = ['id'],
                                     header_file = 'data.hrl',
                                     get_all = True,
                                     processor = mate_processor),
    'Spawnpoint.xls' : ErlRecordConverter('data_spawnpoint',
                                     key_fields = ['id'],
                                     record_name = 'data_spawnpoint',
                                     header_file = 'data.hrl'),
    'Monster.xls' : ErlRecordConverter('data_monster',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    processor = monster_processor),
    'MonsterType.xls' : ErlRecordConverter('data_monster_type',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    processor = monster_type_processor),
    'MonsterAi.xls' : ErlRecordConverter('data_monster_ai',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    processor = monster_ai_processor),
    'Professional.xls' : ErlRecordConverter('data_professional',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    processor = professional_processor),
    'MonsterAttribute.xls' : ErlRecordConverter('data_monster_attribute',
                                    key_fields = ['type', 'level'],
                                    header_file = 'data.hrl',
                                    ),
    'LevelUp.xls' : ErlRecordConverter('basic_fight_values',
                                        key_fields = ['level'],
                                        record_name = 'fight_attribute',
                                        header_file = 'attribute.hrl'),
    'ExpControl.xls' : ErlRecordConverter('data_exp_control',
                                    compare_item = ('world_lv_min', 'world_lv_max'),
                                    key_fields = ['id'],
                                    get_all = True
                                    ),
    'Mate.xls' : ErlRecordConverter('data_mate',
                                     key_fields = ['id'],
                                     header_file = 'data.hrl',
                                     get_all = True,
                                     processor = mate_processor),
    'MateAttribute.xls' : ErlRecordConverter('data_mate_attribute',
                                     key_fields = ['mate_id', 'level'],
                                     header_file = 'data.hrl',
                                     processor = mate_attribute_processor
                                     ),
    'Pet.xls':ErlRecordConverter('data_pet',
                                  key_fields = ['id'],
                                  get_all = True,
                                  ),
    'PetBead.xls':ErlRecordConverter('data_pet_bead',
                                  key_fields = ['id'],
                                  get_all = True,
                                  header_file = 'pet.hrl',
                                  ),
    'PetAttributeSwitch.xls' : ErlRecordConverter('data_pet_attribute_switch',
                                        key_fields = ['class'],
                                        record_name = 'data_attribute_switch',
                                        header_file = 'data.hrl',
                                        include_key_fields = False),
    'SkillAi.xls' : ErlRecordConverter('data_skill_ai',
                                       key_fields = ['id'],
                                       processor = skill_ai_processor),


    'BattleAnger.xls' : ErlSimpleConverter('data_battle_anger',
                                    key_fields = [],
                                    compare_item = ('min', 'max'),
                                    value_field = 'anger_add'
                                    ),
    'PetExp.xls' : ErlSimpleConverter('data_pet_exp',
                                    key_fields = ['level'],
                                    value_field = 'exp'),


    'Shop.xls' : ErlRecordConverter('data_mall',
                                    key_fields = ['shop_item'],
                                    header_file = 'data.hrl',
                                    get_all = True,),

    'MateExp.xls' : ErlSimpleConverter('data_mate_exp',
                                    key_fields = ['level'],
                                    value_field = 'exp'),

    'PetSkillLearn.xls' : ErlRecordConverter('data_pet_skill_learn',
                                    key_fields = ['num'],
                                    header_file = 'pet.hrl'),

    'Mail.xls' : ErlRecordConverter('data_mail',
                                     key_fields = ['id'],
                                     header_file = 'mail.hrl',
                                     get_all = True
                                     ),
    'Equip.xls' : ErlRecordConverter('data_equipment',
                                     key_fields = ['id'],
                                     header_file = 'data.hrl'
                                     ),
    'EquipGems.xls' : ErlRecordConverter('data_equip_gems',
                                     key_fields = ['gem_id'],
                                     header_file = 'data.hrl'
                                     ),
    'EquipStrengthen.xls' : ErlRecordConverter('data_equip_strengthen',
                                     key_fields = ['level'],
                                     header_file = 'data.hrl'
                                     ),
    'EquipPart.xls' : ErlRecordConverter('data_equip_pos',
                                     key_fields = ['id'],
                                     header_file = 'data.hrl'
                                     ),
    'EquipSuit.xls' : ErlRecordConverter('data_equip_suit',
                                     key_fields = ['id'],
                                     header_file = 'data.hrl'
                                     ),
    'EquipSuitCost.xls' : ErlRecordConverter('data_equip_suit_cost',
                                     key_fields = ['type','pos'],
                                     header_file = 'data.hrl'
                                     ),
    'EquipBuild.xls' :ErlRecordConverter('data_equip_achievement',
                                    compare_item = ('min',None),
                                    key_fields = ['type'],
                                    header_file = 'data.hrl'
                                    ),
    'EquipPoint.xls' : ErlRecordConverter('data_equip_lv',
                                    key_fields = ['equip_lv'],
                                    header_file = 'data.hrl'
                                    ),
    'Npc.xls' : ErlRecordConverter('data_npc',
                                     key_fields = ['id'],
                                     header_file = 'data.hrl',
                                     get_all = True,
                                     processor = npc_processor,
                                     ),
    'Task.xls' : ErlRecordConverter('data_task',
                                     key_fields = ['id'],
                                     header_file = 'data.hrl',
                                     get_all = True
                                     ),

    'TeamHallTarget.xls' : ErlRecordConverter('data_team_target',
                                     key_fields = ['id'],
                                     header_file = 'team.hrl',
                                    ),

    'Array.xls' : ErlRecordConverter('data_array',
                                     key_fields = ['id'],
                                     header_file = 'data.hrl',
                                     get_all = True
                                    ),

    'Carriage.xls' : ErlRecordConverter('data_carriage',
                                     key_fields = ['id'],
                                     header_file = 'business.hrl',
                                     get_all = True,
                                     processor = carriage_processor,
                                    ),
    'Business.xls' : ErlRecordConverter('data_business',
                                     key_fields = ['id'],
                                     header_file = 'business.hrl',
                                     get_all = True,
                                    ),
    'classMission.xls' : ErlRecordConverter('data_task_class_rw',
                                     key_fields = ['level', 'loopnum', 'tasknum'],
                                     header_file = 'data.hrl'
                                     ),

    'Title.xls' : ErlRecordConverter('data_title',
                                     key_fields = ['title_id'],
                                     header_file = 'data.hrl',
                                     get_all = True,
                                     processor = title_processor
                                    ),
    'Lifetype.xls' : ErlRecordConverter('data_life_type',
                                     key_fields = ['id'],
                                     header_file = 'data.hrl',
                                     get_all = True
                                    ),
    'Lifeskill.xls' : ErlRecordConverter('data_life_skill',
                                     key_fields = ['id'],
                                     header_file = 'data.hrl',
                                     get_all = True
                                    ),
    'Challenge.xls' : ErlSimpleConverter('data_challenge',
                                    key_fields = ['id'],
                                    value_field = 'monster'
                                    ),
    'Sex.xls' : ErlRecordConverter('data_sex',
                                    key_fields = ['sex_id'],
                                    header_file = 'data.hrl'
                                    ),
    'PetExp.xls' :  ErlRecordConverter('data_pet_exp',
                                     key_fields = ['level'],
                                     header_file = 'data.hrl'
                                    ),
    'PetHorse.xls' : ErlRecordConverter('data_pet_horse',
                                     key_fields = ['level', 'type'],
                                     header_file = 'data.hrl',
                                    ),
    'PetChange.xls' : ErlRecordConverter('data_pet_change',
                                     key_fields = ['type_id', 'rank_petchange'],
                                     header_file = 'data.hrl',
                                    ),
    'SceneMonster.xls' : ErlRecordConverter('data_scene_monster',
                                    key_fields = ['id'],
                                    header_file = 'monster.hrl',
                                    ),
    'Gather.xls' : ErlRecordConverter('data_gather',
                                    key_fields = ['id'],
                                    header_file = 'gather.hrl',
                                    get_all = True,
                                    ),
    'SceneGather.xls' : ErlRecordConverter('data_scene_gather',
                                    key_fields = ['id'],
                                    header_file = 'gather.hrl',
                                    ),
    'Drop.xls' : ErlRecordConverter('data_drop',
                                    key_fields = ['id'],
                                    get_all = True,
                                    header_file = 'drop.hrl',
                                    ),
    'Vip_lv.xls' : ErlRecordConverter('data_vip',
                                    key_fields = ['level'],
                                    header_file = 'data.hrl',
                                    get_all = True,
                                    ),
    'Instance.xls' : ErlRecordConverter('data_instance',
                                    key_fields = ['id'],
                                    header_file = 'instance.hrl',
                                    get_all = True,
                                    ),
    'InstanceType.xls' : ErlRecordConverter('data_instance_type',
                                    key_fields = ['id'],
                                    header_file = 'instance.hrl',
                                    get_all = True,
                                    ),
    'Formula.xls' : ErlRecordConverter('data_formula',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    ),
    'Fate_function.xls' :  ErlRecordConverter('data_fate_function',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    get_all = True,
                                    ),
    'Fate.xls' : ErlRecordConverter('data_fate',
                                    key_fields = ['item_id','level'],
                                    header_file = 'data.hrl',
                                    ),
    'Activity.xls' : ErlRecordConverter('data_activity',
                                    key_fields = ['id'],
                                    header_file = 'activity.hrl',
                                    get_all = True,
                                    ),
    'Activity_lv.xls' : ErlRecordConverter('data_activity_lv',
                                    key_fields = ['level'],
                                    header_file = 'activity.hrl',
                                    ),
    'Activity_Reward.xls' : ErlSimpleConverter('data_activity_rw',
                                    key_fields = ['id'],
                                    value_field = 'reward',
                                    get_all = True,),
    'Activity_zhaohui.xls' :ErlRecordConverter('data_activity_back_rw',
                                    compare_item = ('lv',None),
                                    key_fields = ['group_id'],
                                    header_file = 'activity.hrl'
                                    ),
    'PetFashion.xls' : ErlRecordConverter('data_pet_fashion',
                                     key_fields = ['level', 'type'],
                                     header_file = 'data.hrl',
                                     get_all = True
                                    ),
    'BattlePoint.xls' : ErlRecordConverter('data_battle_point',
                                     key_fields = ['attr'],
                                     header_file = 'data.hrl',
                                     processor = battle_point_processor,
                                    ),
    'Attr_standard.xls' : ErlRecordConverter('data_attr_standard',
                                     key_fields = ['lv'],
                                     header_file = 'data.hrl',
                                    ),
    'Attr_boss.xls' : ErlRecordConverter('data_attr_boss',
                                     key_fields = ['lv'],
                                     header_file = 'data.hrl',
                                    ),
    'FunctionOpen.xls' : ErlRecordConverter('data_function_open',
                                     key_fields = ['id'],
                                     header_file = 'data.hrl',
                                     get_all = True
                                    ),
    'Sign_Month.xls' : ErlRecordConverter('data_sign_month',
                                     key_fields = ['id'],
                                     header_file = 'welfare.hrl',
                                     get_all = True
                                    ),
    'Seven_Login.xls' : ErlRecordConverter('data_seven_login',
                                     key_fields = ['id'],
                                     header_file = 'welfare.hrl',
                                     get_all = True
                                    ),
    'LevelSpurt.xls' : ErlRecordConverter('data_level_spurt',
                                     key_fields = ['id'],
                                     header_file = 'welfare.hrl',
                                     get_all = True
                                    ),
    'Market.xls' : ErlRecordConverter('data_market',
                                    key_fields = ['id'],
                                    header_file = 'market.hrl',
                                     get_all = True
                                    ),
    'Intimacy.xls' : ErlRecordConverter('data_intimacy',
                                    header_file = 'friend.hrl',
                                    compare_item = ('need',None),
                                    key_fields = []
                                    ),
    'Xunbao.xls' : ErlRecordConverter('data_xunbao',
                                    key_fields = ['type'],
                                    compare_item = ('min_level','max_level'),
                                    header_file = 'findtreasure.hrl',
                                    ),
    'EscortMission.xls' : ErlRecordConverter('data_escort_mission',
                                    key_fields = ['id'],
                                    header_file = 'escort.hrl'
                                    ),
    'EscortEvent.xls' : ErlRecordConverter('data_escort_event',
                                    key_fields = ['id'],
                                    header_file = 'escort.hrl'
                                    ),
    'XunbaoCost.xls' : ErlRecordConverter('data_xunbao_cost',
                                    key_fields = ['id'],
                                    header_file = 'findtreasure.hrl',
                                    ),
    'Marry.xls' : ErlRecordConverter('data_marry',
                                    key_fields = ['id'],
                                    header_file = 'marriage.hrl',
                                    get_all = True,
                                    ),
    'XunbaoFate.xls' : ErlRecordConverter('data_xunbao_fate',
                                    key_fields = [],
                                    compare_item = ('min_layer','max_layer'),
                                    header_file = 'findtreasure.hrl',
                                    ),
    'XunbaoMall.xls' : ErlRecordConverter('data_xunbao_mall',
                                    key_fields = ['id'],
                                    header_file = 'findtreasure.hrl',
                                    ),

    'Nine_Tower.xls' : ErlRecordConverter('data_nine_tower',
                                    key_fields = ['id'],
                                    header_file = 'demon_tower.hrl',
                                    get_all = True,
                                    ),
    'MatchArenaRank.xls' : ErlRecordConverter('data_match_arena_rank',
                                    key_fields = [],
                                    compare_item = ('minscore','maxscore'),
                                    header_file = 'peak_match.hrl',
                                    ),

    'Elf.xls' : ErlRecordConverter('data_elf',
                                    key_fields = ['id'],
                                    header_file = 'elf.hrl',
                                    get_all = True,
                                    ),
    'ElfEquip.xls' : ErlRecordConverter('data_elf_equip',
                                    key_fields = ['id'],
                                    header_file = 'elf.hrl'
                                    ),
    'ElfEquipSmelt.xls' : ErlRecordConverter('data_elf_equip_strengthen',
                                    key_fields = ['level'],
                                    header_file = 'elf.hrl'
                                    ),
    'Rank.xls' : ErlRecordConverter('data_rank',
                                    key_fields = ['id'],
                                    header_file = 'rank.hrl',
                                    ),
    'Achievement_Total.xls' : ErlRecordConverter('data_achievement_points_rw',
                                    key_fields = ['id'],
                                    header_file = 'achievement.hrl'
                                    ),
    'Achievement.xls' : ErlRecordConverter('data_achievement',
                                    key_fields = ['id'],
                                    header_file = 'achievement.hrl',
                                    get_all = True,
                                    ),
    'State.xls' :  ErlRecordConverter('data_state',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    ),
    'WorldLv.xls' : ErlRecordConverter('data_world_lv',
                                    key_fields = [],
                                    compare_item = ('min_day','max_day'),
                                    header_file = 'data.hrl',
                                    ),
    'WorldLvExp.xls' : ErlRecordConverter('data_world_lv_exp',
                                    key_fields = [],
                                    compare_item = ('min_lv','max_lv'),
                                    header_file = 'data.hrl',
                                    ),
    'TestReward.xls' : ErlRecordConverter('data_test_reward',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    get_all = True,
                                    ),
    'TestRankReward.xls' :  ErlRecordConverter('data_test_rank_reward',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    get_all = True,
                                    ),
    'Career_Lv.xls' :  ErlRecordConverter('data_trans',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    ),
    'Career_Dragon.xls' :  ErlRecordConverter('data_dragon_soul',
                                    key_fields = ['lv'],
                                    header_file = 'data.hrl',
                                    ),
    'MonsterRebornCtrl.xls' :  ErlRecordConverter('data_monster_reborn_ctrl',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    ),
    'SevenActivity.xls' : ErlRecordConverter('data_seven_activity',
                                    key_fields = ['id'],
                                    header_file = 'seven_day.hrl',
                                    get_all = True,
                                    ),
     'Fiveelement.xls':ErlRecordConverter('data_five_element',
                                    key_fields = ['id'],
                                    header_file = 'five_element.hrl',
                                    get_all = True,
                                    ),
    'MonthCard.xls' : ErlSimpleConverter('data_month_card',
                                    key_fields = ['day'],
                                    value_field = 'rewards'),
     'Investment.xls':ErlRecordConverter('data_investment',
                                    key_fields = ['type', 'level'],
                                    header_file = 'data.hrl',
                                    ),
    'Recharge.xls' : ErlRecordConverter('data_recharge',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    get_all = True,
                                    ),
    'Arena_Rank.xls' : ErlRecordConverter('data_arena_rank',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    get_all = True,
                                    ),
    'MarryHeartLock.xls' : ErlRecordConverter('data_marry_heart_lock',
                                    key_fields = ['lv'],
                                    header_file = 'marriage.hrl',
                                    get_all = True,
                                    ),
    'MarryTitle.xls' : ErlRecordConverter('data_marry_title',
                                    key_fields = ['title_id'],
                                    header_file = 'marriage.hrl',
                                    get_all = True,
                                    ),
    'Pray.xls' : ErlRecordConverter('data_pray',
                                    key_fields = ['times'],
                                    header_file = 'data.hrl',
                                    get_all = True,
                                    ),
    'Soul.xls' : ErlRecordConverter('data_soul',
                                    key_fields = ['item_id', 'level'],
                                    header_file = 'soul_equip.hrl',
                                    get_all = True,
                                    ),
    'EquipGemsRefine.xls' : ErlRecordConverter('data_equip_gems_refine',
                                    key_fields = ['lv'],
                                    header_file = 'data.hrl',
                                    get_all = True,
                                    ),
    'NewbieEvent.xls' : ErlRecordConverter('data_newbie_event',
                                    key_fields = ['order_id'],
                                    header_file = 'event.hrl',
                                    get_all = True,
                                    record_name = 'data_event',
                                    ),
    'Xunbaokaifu.xls' : ErlRecordConverter('data_xunbao_kaifu',
                                    key_fields = ['day'],
                                    compare_item = ('min_level','max_level'),
                                    header_file = 'findtreasure.hrl',
                                    ),
    'ActivityMain.xls' : ErlRecordConverter('data_activity_main',
                                    key_fields = ['id'],
                                    header_file = 'crazy_activity.hrl',
                                    get_all = True,
                                    ),
    'ActivityContent.xls' : ErlRecordConverter('data_activity_content',
                                    key_fields = ['id'],
                                    header_file = 'crazy_activity.hrl',
                                    get_all = True,
                                    ),
    'ActivityReward.xls' : ErlRecordConverter('data_activity_reward',
                                    key_fields = ['id'],
                                    header_file = 'crazy_activity.hrl',
                                    get_all = True,
                                    ),
    'ActivityHigh.xls' : ErlRecordConverter('data_activity_high',
                                    key_fields = ['id'],
                                    header_file = 'crazy_activity.hrl',
                                    get_all = True,
                                    ),
    'ActivityServer.xls' : ErlRecordConverter('data_activity_server',
                                    key_fields = ['id'],
                                    header_file = 'crazy_activity.hrl',
                                    get_all = True,
                                    ),
    'ActivityFireworks.xls' : ErlRecordConverter('data_activity_fireworks',
                                    key_fields = ['id'],
                                    header_file = 'crazy_activity.hrl',
                                    get_all = True,
                                    ),
    'ActivityRank.xls' : ErlRecordConverter('data_activity_rank',
                                    key_fields = ['id'],
                                    header_file = 'crazy_activity.hrl',
                                    get_all = True,
                                    ),
    'Checkpoint.xls' : ErlRecordConverter('data_checkpoint',
                                    key_fields = ['id'],
                                    header_file = 'checkpoint.hrl',
                                    get_all = True
                                    ),
    'ShareReward.xls' : ErlRecordConverter('data_share_reward',
                                    key_fields = ['id'],
                                    header_file = 'share.hrl',
                                    get_all = True
                                    ),
    'Share.xls' : ErlRecordConverter('data_share',
                                    key_fields = ['id'],
                                    header_file = 'share.hrl',
                                    get_all = True
                                    ),
	'ShopDayLimit.xls' : ErlRecordConverter('data_shop_daylimit',
                                    key_fields = ['day','type'],
                                    header_file = 'data.hrl',
                                    get_all = True
                                    ),
	'ShopDayLimitType.xls' : ErlRecordConverter('data_shop_daylimit_type',
                                    key_fields = ['type'],
                                    header_file = 'data.hrl',
                                    get_all = True
                                    ),
	'GangBattleRank.xls' : ErlRecordConverter('data_gangbattle_rank',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    get_all = True
                                    ),
        'CommerceCompany.xls' : ErlRecordConverter('data_commerce_company',
                                    key_fields = ['level'],
                                    header_file = 'data.hrl',
                                    get_all = True
                                    ),
        'CommerceLand.xls' : ErlRecordConverter('data_commerce_land',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    get_all = True
                                    ),
        'CommerceBuilding.xls' : ErlRecordConverter('data_commerce_building',
                                    key_fields = ['id', 'level'],
                                    header_file = 'data.hrl',
                                    get_all = True
                                    ),
        'CommerceBuildingStar.xls' : ErlRecordConverter('data_commerce_building_star',
                                    key_fields = ['id', 'star'],
                                    header_file = 'data.hrl',
                                    get_all = True
                                    ),
        'CommerceEmployeeMarket.xls' : ErlRecordConverter('data_commerce_employee_market',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    get_all = True
                                    ),
        'CommerceEmployee.xls' : ErlRecordConverter('data_commerce_employee',
                                    key_fields = ['id'],
                                    header_file = 'data.hrl',
                                    get_all = True
                                    ),
        'CommerceEmployeeLevel.xls' : ErlRecordConverter('data_commerce_employee_level',
                                    key_fields = ['level', 'quality'],
                                    header_file = 'data.hrl',
                                    get_all = True
                                    ),
        'CommerceEmployeeStar.xls' : ErlRecordConverter('data_commerce_employee_star',
                                    key_fields = ['star', 'quality'],
                                    header_file = 'data.hrl',
                                    get_all = True
                                    ),
}

def export(xls, fields, records, types):
    if xls not in exporters:
        print('(erl) no exporter defined for %s' % (xls, ))
        return

    exporters[xls].export(fields, records, types)
