from json_exporter import JsonRecordExporter
from json_processor import *

import os
import sys

exporters = {
        'Item.xls' : JsonRecordExporter(basename = 'items',
            key_field = 'id',
            # processor = item_processor
            ),
        'Farm.xls' : JsonRecordExporter(basename = "farm",
            key_field = 'level',
            processor = default_processor),
        'JumpPoint.xls' : JsonRecordExporter(basename = "jump_point",
            key_field = 'id',
            processor = jumppoint_processor),
        'Npc.xls' : JsonRecordExporter(basename = "npc",
            key_field = 'id',
            processor = npc_processor),
        'FunctionCondition.xls' : JsonRecordExporter(basename = "functionCondition",
            key_field = 'id',
            processor = functioncondition_processor),
        'Scene.xls' : JsonRecordExporter(basename = "scene",
            key_field = 'id',
            # processor = scene_processor
            ),
        'Skill.xls' : JsonRecordExporter(basename = "skill",
            key_field = 'id',
            # processor = default_processor
            ),
        'Skill_effect.xls' : JsonRecordExporter(basename = "skillEffect",
            key_field = 'id',
            processor = default_processor),
        'SkillLearn.xls' : JsonRecordExporter(basename = "skill_learn",
            key_field = 'skill_group',
            processor = skill_learn_processor),
        'Exp.xls' : JsonRecordExporter(basename = "exp",
            key_field = 'level',
            # processor = exp_processor
            ),
        'Skill_Core.xls' : JsonRecordExporter(basename = "core_skill",
            key_field = 'id',
            processor = default_processor),
        'AttributeSwitch.xls' : JsonRecordExporter(basename = "attributeSwitch",
            key_field = 'class',
            processor = default_processor),
        'Character_recommend.xls' : JsonRecordExporter(basename = "characterRecommend",
            key_field = 'id',
            processor = default_processor),
        'PetExp.xls' : JsonRecordExporter(basename = "pet_exp",
            key_field = 'level',
            ),
        'Pet.xls' : JsonRecordExporter(basename = "petBase",
            key_field = 'id',),
        'Mate.xls' : JsonRecordExporter(basename = 'mate',
            key_field = 'id',
            #processor = default_processor
            ),
        'MateAttribute.xls' : JsonRecordExporter(basename = 'mate_attribute',
                key_field = 'id',
                processor = mate_attribute_processor
                ),
        'Class.xls' : JsonRecordExporter(basename = "classBase",
                key_field = 'class',
                processor = default_processor),
        'SkillLearnCost.xls' : JsonRecordExporter(basename = "skillLearnCost",
                key_field = 'lv',
                processor = default_processor),
        'MateExp.xls' : JsonRecordExporter(basename = 'mate_exp',
                key_field = 'level',
                #processor = default_processor
                ),
        'Shop.xls' : JsonRecordExporter(basename = 'shop',
                key_field = 'shop_item',
                #processor = default_processor
                ),
        'Mail.xls' : JsonRecordExporter(basename = 'mail',
                key_field = 'id',
                #processor = default_processor
                ),
        'Buff.xls' : JsonRecordExporter(basename = 'buff',
                key_field = 'id',
                processor = buff_processor
                ),
        'PetAttributeSwitch.xls' : JsonRecordExporter(basename = 'petAttributeSwitch',
                key_field = 'class',
                #processor = default_processor
                ),
        'ClassModel.xls' : JsonRecordExporter(basename = 'class_model',
                key_field = 'id',
                processor = class_model_processor
                ),
        'Monster.xls' : JsonRecordExporter(basename = 'monster',
                key_field = 'id',
                #processor = default_processor
                ),
        'MissionSetting.xls' : JsonRecordExporter(basename = "missionsetting",
                key_field = 'id',
                processor = missionsetting_processor),
        'Equip.xls' : JsonRecordExporter(basename = "equip_cfg",
                key_field = 'id',
                ),
        'AttributeDescribe.xls' : JsonRecordExporter(basename = "attributeDescribe",
                key_field = 'id',
                processor = default_processor),
        'EquipGems.xls' : JsonRecordExporter(basename = "equip_gems",
                key_field = 'gem_id',
                #processor = equipGems_processor
                ),
        'TeamHallTarget.xls' : JsonRecordExporter(basename = "teamHallTarget",
                key_field = 'id',
                # processor = default_processor
                ),
        'Announcement.xls' : JsonRecordExporter(basename = "announcement",
                key_field = 'id',
                processor = announcement_processor),
        'Mission.xls' : JsonRecordExporter(basename = "mission",
                key_field = 'id',
                # processor = mission_processor
                ),
        'Array.xls' : JsonRecordExporter(basename = "array",
                key_field = 'id',
                processor = array_processor),
        'Names.xls' : JsonRecordExporter(basename = "names",
                key_field = 'id',
                processor = default_processor),
        'Dialogue.xls' : JsonRecordExporter(basename = "dialogue",
                key_field = 'id',
                processor = default_processor),
        'PetBead.xls' : JsonRecordExporter(basename = "petBead",
                key_field = 'id',
                processor = default_processor),
        'AttributeTrans.xls' : JsonRecordExporter(basename = "attributeTrans",
                key_field = 'server_attr',
                processor = default_processor),
        'PetBook.xls' : JsonRecordExporter(basename = "petBook",
                key_field = 'id',
                processor = default_processor),
        'JumpTo.xls' : JsonRecordExporter(basename = "jumpTo",
                key_field = 'id',
                processor = jump_to_processor),
        'Title.xls' : JsonRecordExporter(basename = "title",
                key_field = 'title_id',
                processor = title_processor),
        'Lifeskill.xls' : JsonRecordExporter(basename = "lifeskill",
                key_field = 'id',
                ),
        'Lifetype.xls' : JsonRecordExporter(basename = "lifetype",
                key_field = 'id',
                ),
        'Business.xls' : JsonRecordExporter(basename = "businessGoods",
                key_field = 'id',
                processor = default_processor),
        'Carriage.xls' : JsonRecordExporter(basename = "carriage",
                key_field = 'id',
                processor = default_processor),
        'Gather.xls' : JsonRecordExporter(basename = "gather",
                key_field = 'id',
                ),
        'Drop.xls' : JsonRecordExporter(basename = "drop",
                key_field = 'id',
                processor = default_processor),
        'Sex.xls' : JsonRecordExporter(basename = "sex",
                key_field = 'sex_id',
                ),
        'PetHorse.xls' : JsonRecordExporter(basename = "petHorse",
                key_field = 'id',
                ),
        'PetChange.xls' : JsonRecordExporter(basename = "petChange",
                key_field = 'id',
                ),
        'FunctionIcon.xls' : JsonRecordExporter(basename = "functionIcon",
                key_field = 'id',
                processor = default_processor),
        'EquipStrengthen.xls' : JsonRecordExporter(basename = "strengthen",
                key_field = 'level',
                ),
        'EquipPart.xls' : JsonRecordExporter(basename = "equip_part",
                key_field = 'id',
                ),
        'Compose.xls' : JsonRecordExporter(basename = "compose",
                key_field = 'compose_id',
                ),
        'EquipSuit.xls' : JsonRecordExporter(basename = "suit",
                key_field = 'id',
                ),
        'FlyPoint.xls' : JsonRecordExporter(basename = "flyPoint",
                key_field = 'id',
                ),
        'MatchArenaRank.xls' : JsonRecordExporter(basename = "matcharenarank",
                key_field = 'id',
                ),
        'GangBattleWin.xls' : JsonRecordExporter(basename = "gangbattlewin",
                key_field = 'id',
                ),
        'SevenActivity.xls' : JsonRecordExporter(basename = "sevenactivity",
                key_field = 'id',
                ),
        'Activity_Calendar' : JsonRecordExporter(basename = "activityCalendar",
                key_field = 'id',
                ),
        'NoviceStep.xls' : JsonRecordExporter(basename = "novicestep",
                key_field = 'id',
                ),
        'ShareWechat.xls' : JsonRecordExporter(basename = "sharewechat",
                key_field = 'id',
                ),
        'Words.xls' : JsonRecordExporter(basename = "words",
                key_field = 'id',
                ),
        'MonsterAi.xls' : JsonRecordExporter(basename = "monsterai",
                key_field = 'id',
                ),
        'Xunbaokaifu.xls' : JsonRecordExporter(basename = "xunbaokaifu",
                key_field = 'id',
                ),
        'ActivityContent.xls' : JsonRecordExporter(basename = "activitycontent",
                key_field = 'id',
                ),
        'Checkpoint.xls' : JsonRecordExporter(basename = "checkpoint",
                key_field = 'id',
                ),
        'ActivityMain.xls' : JsonRecordExporter(basename = "activitymain",
                key_field = 'id',
                ),
        'ActivityReward.xls' : JsonRecordExporter(basename = "activityreward",
                key_field = 'id',
                ),
        'ActivityHigh.xls' : JsonRecordExporter(basename = "activityhigh",
                key_field = 'id',
                ),
        'ActivityServer.xls' : JsonRecordExporter(basename = "activityserver",
                key_field = 'id',
                ),
        'ShareReward.xls' : JsonRecordExporter(basename = "shareReward",
                key_field = 'id',
                ),
        'ShareBackReward.xls' : JsonRecordExporter(basename = "shareBackReward",
                key_field = 'id',
                ),
        'Share.xls' : JsonRecordExporter(basename = "share",
                key_field = 'id',
                ),
        'ActivityRank.xls' : JsonRecordExporter(basename = "activityrank",
                key_field = 'id',
                ),
        'CommerceCompany.xls' : JsonRecordExporter(basename = 'commerceCompany',
                key_field = 'level',
                ),
        'CommerceBuilding.xls' : JsonRecordExporter(basename = 'commerceBuilding',
                key_field = 'id',
                ),
        'CommerceBuildingStar.xls' : JsonRecordExporter(basename = 'commerceBuildingStar',
                key_field = 'id',
                ),
        'CommerceCompanyLand.xls' : JsonRecordExporter(basename = 'commerceLand',
                key_field = 'id',
                ),
        'CommerceEmployeeMarket.xls' : JsonRecordExporter(basename = 'commerceEmployeeMarket',
                key_field = 'id',
                ),
        'CommerceEmployee.xls' : JsonRecordExporter(basename = 'commerceEmployee',
                key_field = 'id',
                ),
        'CommerceEmployeeLevel.xls' : JsonRecordExporter(basename = 'commerceEmployeeLevel',
                key_field = 'id',
                ),
        'CommerceEmployeeStar.xls' : JsonRecordExporter(basename = 'commerceEmployeeStar',
                key_field = 'id',
                ),
        }


def export(xls, fields, records, types):
    if xls not in exporters:
        print('(json) no exporter defined for %s' % (xls, ))
        if(len(fields)>0):
            basename = xls.split(".")[0].lower()
            key_field = fields[0]
            print('(json) use default basename: %s key_field: %s'% (basename, key_field,))
            JsonRecordExporter(basename = basename,
                                key_field = key_field,
                                ).export(fields, records, types)
    else:
        exporters[xls].export(fields, records, types)

